version: '3.4'

networks:
  rest-api-dev:
    driver: bridge

services:
  restapi:
    image: ${DOCKER_REGISTRY-}restapi
    build:
      context: .
      dockerfile: RestApi/Dockerfile
    depends_on:
      - "mysql"
    ports:
      - "8000:80"
    networks:
      - rest-api-dev

  mysql:
    image: mysql:8
    restart: unless-stopped
    ports:
      - "8012:3306"
    environment:
      MYSQL_DATABASE: rest-api
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - database:/var/lib/mysql
    networks:
      - rest-api-dev

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8013:80"
    links:
      - mysql:mysql
    environment:
      PMA_HOST: mysql
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: root
    networks:
      - rest-api-dev

volumes:
  database: